<?php
// PGS = Pages or Groups or Subjects
Route::get('list', ['as' => 'pgs.desktop.hamahang.tasks.my_tasks.list', 'uses' => 'MyTaskController@MyTasksList', 'middleware' => ['dynamic_permission:pgs.desktop.hamahang.tasks.my_tasks.list']]);
Route::get('AllList', ['as' => 'pgs.desktop.hamahang.tasks.my_tasks.all_task_list', 'uses' => 'MyTaskController@ListAllTask', 'middleware' => ['dynamic_permission:pgs.desktop.hamahang.tasks.my_tasks.list']]);
Route::get('AllListState', ['as' => 'pgs.desktop.hamahang.tasks.my_tasks.all_task_state', 'uses' => 'MyTaskController@ListAllTaskState', 'middleware' => ['dynamic_permission:pgs.desktop.hamahang.tasks.my_tasks.list']]);
Route::get('AllTaskPriority', ['as' => 'pgs.desktop.hamahang.tasks.my_tasks.all_task_priority', 'uses' => 'MyTaskController@ListAllTaskPriority', 'middleware' => ['dynamic_permission:pgs.desktop.hamahang.tasks.my_tasks.list']]);
Route::get('transcripts', ['as' => 'pgs.desktop.hamahang.tasks.my_tasks.transcripts_list', 'uses' => 'MyTaskController@get_transcripts', 'middleware' => ['dynamic_permission:pgs.desktop.hamahang.tasks.my_tasks.list']]);
Route::get('priority', ['as' => 'pgs.desktop.hamahang.tasks.my_tasks.priority', 'uses' => 'MyTaskController@MyTasksPriority', 'middleware' => ['dynamic_permission:pgs.desktop.hamahang.tasks.my_tasks.priority']]); ////// user_tasks
Route::get('state', ['as' => 'pgs.desktop.hamahang.tasks.my_tasks.state', 'uses' => 'MyTaskController@MyTasksState', 'middleware' => ['dynamic_permission:pgs.desktop.hamahang.tasks.my_tasks.state']]); ////// user tasks state
Route::get('package', ['as' => 'pgs.desktop.hamahang.tasks.my_tasks.package', 'uses' => 'PackageController@MyTaskPackages', 'middleware' => ['dynamic_permission:pgs.desktop.hamahang.tasks.my_tasks.package']]); ////// user task packages - pgs.desktop.hamahang.tasks.my_tasks.package